# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/tnsilva/535ae996c8da79ebed87982e0d8888c0/untitled0.ipynb
"""
pip install yfinance

import yfinance as yf

dados = yf.download("WEGE3.SA", start="2017-01-01", end="2021-07-01")

dados['Adj Close'].plot()
